
linters-settings:
  gocritic:
#    disabled-checks:
#      - paramTypeCombine
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - forbidigo

linters:
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - gochecknoinits
    - gocritic
    - gocyclo
    - gofmt
    - golint
    - goprintffuncname
    - gosimple
    - gosec
    - govet
    - ineffassign
    - interfacer
    - makezero
    - maligned
    - megacheck
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - predeclared
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
  fast: false