version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - importas
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - tagalign
    - testifylint
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - perfsprint
          - usestdlibvars
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
