run:
  issues-exit-code: 1

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - exhaustive
    - gochecknoinits
    - gocyclo
    - gofmt
    - golint
    - goprintffuncname
    - gosimple
    - gosec
    - govet
    - ineffassign
    - interfacer
    - maligned
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wsl

issues:
  new: true
