// Code generated by mockery v1.0.0
package mocks

import gojenkins "github.com/brainexe/gojenkins"

import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// BuildJob provides a mock function with given fields: name, options
func (_m *Client) BuildJob(name string, options ...interface{}) (int64, error) {
	var _ca []interface{}
	_ca = append(_ca, name)
	_ca = append(_ca, options...)
	ret := _m.Called(_ca...)

	var r0 int64
	if rf, ok := ret.Get(0).(func(string, ...interface{}) int64); ok {
		r0 = rf(name, options...)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, ...interface{}) error); ok {
		r1 = rf(name, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllNodes provides a mock function with given fields:
func (_m *Client) GetAllNodes() ([]*gojenkins.Node, error) {
	ret := _m.Called()

	var r0 []*gojenkins.Node
	if rf, ok := ret.Get(0).(func() []*gojenkins.Node); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gojenkins.Node)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJob provides a mock function with given fields: id, parentIDs
func (_m *Client) GetJob(id string, parentIDs ...string) (*gojenkins.Job, error) {
	_va := make([]interface{}, len(parentIDs))
	for _i := range parentIDs {
		_va[_i] = parentIDs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *gojenkins.Job
	if rf, ok := ret.Get(0).(func(string, ...string) *gojenkins.Job); ok {
		r0 = rf(id, parentIDs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gojenkins.Job)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, ...string) error); ok {
		r1 = rf(id, parentIDs...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetQueue provides a mock function with given fields:
func (_m *Client) GetQueue() (*gojenkins.Queue, error) {
	ret := _m.Called()

	var r0 *gojenkins.Queue
	if rf, ok := ret.Get(0).(func() *gojenkins.Queue); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gojenkins.Queue)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
