// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	msg "github.com/innogames/slack-bot/v2/bot/msg"
	mock "github.com/stretchr/testify/mock"

	slack "github.com/slack-go/slack"

	util "github.com/innogames/slack-bot/v2/bot/util"
)

// SlackClient is an autogenerated mock type for the SlackClient type
type SlackClient struct {
	mock.Mock
}

// AddReaction provides a mock function with given fields: reaction, ref
func (_m *SlackClient) AddReaction(reaction util.Reaction, ref msg.Ref) {
	_m.Called(reaction, ref)
}

// CanHandleInteractions provides a mock function with given fields:
func (_m *SlackClient) CanHandleInteractions() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GetConversationHistory provides a mock function with given fields: _a0
func (_m *SlackClient) GetConversationHistory(_a0 *slack.GetConversationHistoryParameters) (*slack.GetConversationHistoryResponse, error) {
	ret := _m.Called(_a0)

	var r0 *slack.GetConversationHistoryResponse
	if rf, ok := ret.Get(0).(func(*slack.GetConversationHistoryParameters) *slack.GetConversationHistoryResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slack.GetConversationHistoryResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*slack.GetConversationHistoryParameters) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReactions provides a mock function with given fields: item, params
func (_m *SlackClient) GetReactions(item slack.ItemRef, params slack.GetReactionsParameters) ([]slack.ItemReaction, error) {
	ret := _m.Called(item, params)

	var r0 []slack.ItemReaction
	if rf, ok := ret.Get(0).(func(slack.ItemRef, slack.GetReactionsParameters) []slack.ItemReaction); ok {
		r0 = rf(item, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]slack.ItemReaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(slack.ItemRef, slack.GetReactionsParameters) error); ok {
		r1 = rf(item, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveReaction provides a mock function with given fields: reaction, ref
func (_m *SlackClient) RemoveReaction(reaction util.Reaction, ref msg.Ref) {
	_m.Called(reaction, ref)
}

// ReplyError provides a mock function with given fields: ref, err
func (_m *SlackClient) ReplyError(ref msg.Ref, err error) {
	_m.Called(ref, err)
}

// SendBlockMessage provides a mock function with given fields: ref, blocks, options
func (_m *SlackClient) SendBlockMessage(ref msg.Ref, blocks []slack.Block, options ...slack.MsgOption) string {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ref, blocks)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 string
	if rf, ok := ret.Get(0).(func(msg.Ref, []slack.Block, ...slack.MsgOption) string); ok {
		r0 = rf(ref, blocks, options...)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SendEphemeralMessage provides a mock function with given fields: ref, text, options
func (_m *SlackClient) SendEphemeralMessage(ref msg.Ref, text string, options ...slack.MsgOption) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ref, text)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// SendMessage provides a mock function with given fields: ref, text, options
func (_m *SlackClient) SendMessage(ref msg.Ref, text string, options ...slack.MsgOption) string {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ref, text)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 string
	if rf, ok := ret.Get(0).(func(msg.Ref, string, ...slack.MsgOption) string); ok {
		r0 = rf(ref, text, options...)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SendToUser provides a mock function with given fields: user, text
func (_m *SlackClient) SendToUser(user string, text string) {
	_m.Called(user, text)
}
