package builder

import (
	"bytes"
	"context"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"text/template"
)

// moduleName of the generated Go module
const moduleName = "slack-bot-custom"

var mainTemplate = template.Must(template.New("main").Parse(`// Code generated by slack-bot-builder. DO NOT EDIT.

package main

import (
	"{{.Package}}"
{{range .Imports}}
	// {{.Comment}}
	_ "{{.Path}}"
{{end}}
)

func main() {
	{{.Call}}
}
`))

type mainImport struct {
	Path    string
	Comment string
}

// initModule creates the go.mod with the requirement of the slack-bot core.
// The go.mod is always generated from scratch, only the go.sum is kept.
func (b *builder) initModule(ctx context.Context, core coreSource) error {
	if err := os.Remove(filepath.Join(b.workDir, "go.mod")); err != nil && !os.IsNotExist(err) {
		return err
	}
	if err := b.runSilent(ctx, b.workDir, "go", "mod", "init", moduleName); err != nil {
		return err
	}

	if core.dir != "" {
		b.coreVersion = b.getLocalCoreVersion(ctx, core.dir)

		return b.runSilent(ctx, b.workDir, "go", append([]string{"mod", "edit"}, getReplaceArgs(CoreModule, core.dir)...)...)
	}

	// resolve the query (like "latest") to a fixed version, before any plugin can influence it
	if err := b.run(ctx, b.workDir, "go", "get", CoreModule+"@"+core.version); err != nil {
		return err
	}

	var err error
	b.coreVersion, err = b.getSelectedCoreVersion(ctx)

	return err
}

// addLocalPlugins replaces the modules of local and git plugins with their directory
func (b *builder) addLocalPlugins(ctx context.Context, plugins []*plugin) error {
	editArgs := []string{"mod", "edit"}

	replaced := map[string]string{}
	for _, p := range plugins {
		if p.moduleDir == "" {
			continue
		}

		if dir, ok := replaced[p.modulePath]; ok {
			if dir != p.moduleDir {
				return fmt.Errorf("module %s is provided by two directories: %s and %s", p.modulePath, dir, p.moduleDir)
			}
			continue
		}
		replaced[p.modulePath] = p.moduleDir

		editArgs = append(editArgs, getReplaceArgs(p.modulePath, p.moduleDir)...)
	}

	if len(replaced) == 0 {
		return nil
	}

	return b.runSilent(ctx, b.workDir, "go", editArgs...)
}

// writeMainPackages generates the main packages of the bot and the CLI
func (b *builder) writeMainPackages(plugins []*plugin) error {
	if err := writeMain(filepath.Join(b.workDir, "cmd", "bot", "main.go"), "github.com/innogames/slack-bot/v2/bot/app", "app.Run()", plugins); err != nil {
		return err
	}

	cliMain := filepath.Join(b.workDir, "cmd", "cli", "main.go")
	if b.opts.CLIOutput == "" {
		return os.RemoveAll(filepath.Dir(cliMain))
	}

	return writeMain(cliMain, "github.com/innogames/slack-bot/v2/bot/cli", "cli.Run()", plugins)
}

// getReplaceArgs to use the local directory for the given module
func getReplaceArgs(modulePath string, dir string) []string {
	return []string{
		"-require=" + modulePath + "@" + getZeroVersion(modulePath),
		"-replace=" + modulePath + "=" + dir,
	}
}

var majorVersionSuffix = regexp.MustCompile(`/v([2-9]|[1-9][0-9]+)$`)

// getZeroVersion returns a placeholder version for a replaced module, it has to match the major version of the module path
func getZeroVersion(modulePath string) string {
	major := "v0"
	if match := majorVersionSuffix.FindStringSubmatch(modulePath); match != nil {
		major = "v" + match[1]
	}

	return major + ".0.0-00010101000000-000000000000"
}

// writeMain generates a main package, which imports all plugins
func writeMain(file string, pkg string, call string, plugins []*plugin) error {
	imports := make([]mainImport, 0, len(plugins))
	for _, p := range plugins {
		comment := fmt.Sprintf("plugin %q (%s)", p.name, p.cfg.Source)

		// multiple plugins can be provided by the same package
		index := slices.IndexFunc(imports, func(i mainImport) bool {
			return i.Path == p.importPath
		})
		if index >= 0 {
			imports[index].Comment += ", " + comment
			continue
		}

		imports = append(imports, mainImport{Path: p.importPath, Comment: comment})
	}

	var buf bytes.Buffer
	err := mainTemplate.Execute(&buf, map[string]any{
		"Package": pkg,
		"Call":    call,
		"Imports": imports,
	})
	if err != nil {
		return err
	}

	source, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}

	if err = os.MkdirAll(filepath.Dir(file), 0o750); err != nil {
		return err
	}

	return os.WriteFile(file, source, 0o600)
}

// printGeneratedFiles is used for a dry run
func (b *builder) printGeneratedFiles() error {
	for _, file := range []string{"go.mod", "cmd/bot/main.go", "cmd/cli/main.go"} {
		content, err := os.ReadFile(filepath.Join(b.workDir, file)) // #nosec G304 -- generated file
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return err
		}

		fmt.Fprintf(b.log, "\n// %s\n%s", file, content)
	}

	return nil
}

// describe the resolved plugin for the log output
func (p *plugin) describe() string {
	switch p.kind {
	case localSource:
		return fmt.Sprintf("package %s from local directory %s", p.importPath, p.moduleDir)
	case gitSource:
		return fmt.Sprintf("package %s from %s (commit %s)", p.importPath, p.cfg.Source, shortCommit(p.commit))
	case moduleSource:
		return fmt.Sprintf("package %s@%s", p.importPath, p.getVersion())
	}

	return p.importPath
}

// getVersion of a module source, default is the latest version
func (p *plugin) getVersion() string {
	if p.cfg.Version == "" {
		return "latest"
	}

	return p.cfg.Version
}

func shortCommit(commit string) string {
	if len(commit) > 12 {
		return commit[:12]
	}

	return strings.TrimSpace(commit)
}
